name: pacman-build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@main
      - uses: egor-tensin/vs-shell@v2
        if: runner.os == 'Windows'
        with:
          arch: x64
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-latest

      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      - name: (Dub) Build
        run: dub build
      - name: build-web
        run: dub build -c wasm --arch wasm32-unknown-emscripten-wasm
