name: pacman-build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-master

      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      # - name: (Dub) Build
      #   run: dub build
      - name: (Zig) Build
        run: zig build --summary all
